### ISSUE TITLE
refactor: reduce code line in setFeeCollector

### ISSUE THREAD

**Issue by ryanycw** [CirculatorLab/contracts#17]
Ping @antoncoding @orbxball to discuss if this is better. And if it's necessary to log the old feeCollector, and should we log previous fees in set...Fee related functions. 

https://github.com/CirculatorLab/contracts/blob/b45264fdac03671795b6e101cf2f440ef1d5d1b0/src/FeeOperator.sol#L36-L41

```
    function setFeeCollector(address _feeCollector) external onlyOwner {
        if (_feeCollector == address(0)) revert InvalidFeeCollector();
        emit FeeCollectorUpdated(feeCollector, _feeCollector);
        feeCollector = _feeCollector;
    }
```

**Comment by orbxball** [comment]
I chatted with Anton on this yesterday. I'm thinking change the feeCollector design to a dev multisig. so i think we can remove this all.

**Comment by orbxball** [comment]
i vote for every change to save gas. thinking removing line 37 & 38 & 40. But I'm also thinking **legitamacy** and **statistics** are both important. We need a balance. If we do not log it, it is probably lower down ppl's trust to the smart contract, thinking the team behind the protocol is not capable enough. 

IMO, the rules of thumb of log and event emission is "whether we need to do statistics". If there is no use case for other devs to read this info for doing statistics, we don't need to log. The only use case of logging this is that we could build a page to accumulate the total profit earned by the protocol. As for previous fee and other places we log info are with similar reasons. It's only for **building statistics**. I agree statistics are important, as we do not change it that frequently, we can log them.

As for the check of `address(0)`, I always think it's extra as we will definitely check before we draft the txn on safe.

**Comment by antoncoding** [comment]
re @orbxball 
1. we don't need address(0) check because we didn't send funds to the address right away 
(usually people need this check because sending token to address(0) will revert, so owner maliciously setting to 0 can cause functions to revert

2. agree that we don't really need events, but this function will only be called like twice in its life time so i don't think it's that important to concern about gas, having event could maybe allow us to setup alarms or notifications when that's changed. but again, i'm not too fuzz about either, keeping it minimum is also good.

re @ryanycw 
I think the bottom line is we don't need to log the old owner. That's always a bad pattern that i don't get. we can just do
```
emit FeeCollectorUpdated(feeCollector, _feeCollector);
feeCollector = _feeCollector;
```

and it would be more than enough
